name: protalign-arg
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.4.0
  - anyio=3.6.2
  - astunparse=1.6.3
  - binutils_impl_linux-64=2.38
  - bio=1.5.5
  - biopython=1.81
  - biothings-client=0.2.6
  - ca-certificates=2023.01.10
  - cachetools=5.3.0
  - certifi=2022.12.7
  - charset-normalizer=3.0.1
  - click=8.1.3
  - configobj=5.0.8
  - cudatoolkit=11.0.3
  - cudnn=8.0.5.39
  - diamond=0.9.14
  - dpcpp-cpp-rt=2023.0.0
  - dpcpp_cpp_rt=2023.0.0
  - emboss=6.6.0
  - expat=2.4.9
  - fastapi=0.95.0
  - filelock=3.9.0
  - flatbuffers=23.1.21
  - fontconfig=2.14.1
  - fortran_rt=2023.0.0
  - freetype=2.12.1
  - gast=0.4.0
  - gcc=12.1.0
  - gcc_impl_linux-64=12.1.0
  - giflib=5.2.1
  - google-auth=2.16.1
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - gprofiler-official=1.0.0
  - graph-part=0.1.2
  - grpcio=1.51.3
  - h11=0.14.0
  - h5py=3.8.0
  - httptools=0.5.0
  - huggingface-hub=0.12.1
  - icc_rt=2023.0.0
  - icu=58.2
  - idna=3.4
  - impi_rt=2021.8.0
  - importlib-metadata=6.0.0
  - intel-cmplr-lib-rt=2023.0.0
  - intel-cmplr-lic-rt=2023.0.0
  - intel-fortran-rt=2023.0.0
  - intel-opencl-rt=2023.0.0
  - intel-openmp=2023.0.0
  - intelpython=2023.0.0
  - jax=0.4.7
  - joblib=1.0.1
  - jpeg=9e
  - keras=2.12.0
  - kernel-headers_linux-64=2.6.32
  - ld_impl_linux-64=2.38
  - lerc=3
  - libclang=15.0.6.1
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.1.0
  - libgcc-ng=12.2.0
  - libgd=2.3.3
  - libgomp=12.2.0
  - libpng=1.6.39
  - libsanitizer=12.1.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.2
  - mkl=2023.0.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mkl_umath=0.1.1
  - ml-dtypes=0.0.4
  - mygene=3.2.2
  - ncurses=6.4
  - networkx=3.1
  - numpy=1.22.4
  - numpy-base=1.22.3
  - nvidia-cuda-nvrtc-cu11=11.7.99
  - nvidia-cuda-runtime-cu11=11.7.99
  - nvidia-cudnn-cu11=8.6.0.163
  - nvidia-pyindex=1.0.9
  - oauthlib=3.2.2
  - openssl=1.1.1t
  - opt-einsum=3.3.0
  - packaging=23
  - pandas=1.5.3
  - pip=23.0.1
  - protobuf=4.22.1
  - psutil=5.9.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pydantic=1.10.7
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-dotenv=1.0.0
  - python-version=0.0.2
  - python_abi=3.9
  - pytz=2022.7.1
  - pyyaml=6
  - readline=8.2
  - regex=2022.10.31
  - requests=2.28.2
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scikit-learn=1.1.1
  - scipy=1.7.3
  - sentencepiece=0.1.97
  - setuptools=65.6.3
  - six=1.16.0
  - sklearn=0.0.post1
  - sniffio=1.3.0
  - sqlite=3.40.1
  - starlette=0.26.1
  - sysroot_linux-64=2.12
  - tbb=2021.8.0
  - tbb4py=2021.8.0
  - tensorboard=2.12.0
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.12.0
  - tensorflow-estimator=2.12.0
  - tensorflow-io-gcs-filesystem=0.31.0
  - termcolor=2.2.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tokenizers=0.13.2
  - torch=1.13.1
  - tqdm=4.64.1
  - transformers=4.26.1
  - typing-extensions=4.5.0
  - tzdata=2022g
  - urllib3=1.26.14
  - uvicorn=0.21.1
  - uvloop=0.17.0
  - watchfiles=0.18.1
  - websockets=10.4
  - werkzeug=2.2.3
  - wheel=0.38.4
  - wrapt=1.14.1
  - xz=5.2.10
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
